# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'front.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(906, 517)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 871, 481))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(21, 21))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 401, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.Browse_BTN = QtWidgets.QPushButton(self.tab_2)
        self.Browse_BTN.setGeometry(QtCore.QRect(580, 10, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.Browse_BTN.setFont(font)
        self.Browse_BTN.setStyleSheet("QPushButton::pressed\n"
"{background-color : rgb(54, 108, 162);\n"
"} \n"
"\n"
" QPushButton{\n"
"background-color: rgb(85, 170, 255);\n"
"border: 2px solid black;\n"
"color: white;padding: 10px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"display: inline-block;\n"
"font-size: 16px;\n"
"margin: 4px 2px;\n"
"cursor: pointer;\n"
"border-radius: 12px;\n"
"}\n"
"\n"
"")
        self.Browse_BTN.setObjectName("Browse_BTN")
        self.textEdit_2 = QtWidgets.QLabel(self.tab_2)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 90, 661, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textEdit_2.setText("")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(20, 50, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(700, 20, 151, 161))
        self.label_8.setStyleSheet("\n"
"background-image: url(:/aa/img.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.online_check_BTN = QtWidgets.QPushButton(self.tab_2)
        self.online_check_BTN.setGeometry(QtCore.QRect(20, 380, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.online_check_BTN.setFont(font)
        self.online_check_BTN.setStyleSheet("QPushButton::pressed\n"
"{background-color : rgb(54, 108, 162);\n"
"} \n"
"\n"
" QPushButton{\n"
"background-color: rgb(85, 170, 255);\n"
"border: 2px solid black;\n"
"color: white;padding: 10px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"display: inline-block;\n"
"font-size: 16px;\n"
"margin: 4px 2px;\n"
"cursor: pointer;\n"
"border-radius: 12px;\n"
"}\n"
"\n"
"")
        self.online_check_BTN.setObjectName("online_check_BTN")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(750, 210, 101, 141))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Exit_BTN = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.Exit_BTN.setFont(font)
        self.Exit_BTN.setStyleSheet("QPushButton::pressed\n"
"{background-color : rgb(54, 108, 162);\n"
"} \n"
"\n"
" QPushButton{\n"
"background-color: rgb(85, 170, 255);\n"
"border: 2px solid black;\n"
"color: white;padding: 10px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"display: inline-block;\n"
"font-size: 16px;\n"
"margin: 4px 2px;\n"
"cursor: pointer;\n"
"border-radius: 12px;\n"
"}\n"
"\n"
"")
        self.Exit_BTN.setObjectName("Exit_BTN")
        self.gridLayout_2.addWidget(self.Exit_BTN, 2, 0, 1, 1)
        self.Generate_BTN = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.Generate_BTN.setFont(font)
        self.Generate_BTN.setStyleSheet("QPushButton::pressed\n"
"{background-color : rgb(54, 108, 162);\n"
"} \n"
"\n"
" QPushButton{\n"
"background-color: rgb(85, 170, 255);\n"
"border: 2px solid black;\n"
"color: white;padding: 10px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"display: inline-block;\n"
"font-size: 16px;\n"
"margin: 4px 2px;\n"
"cursor: pointer;\n"
"border-radius: 12px;\n"
"}\n"
"\n"
"")
        self.Generate_BTN.setObjectName("Generate_BTN")
        self.gridLayout_2.addWidget(self.Generate_BTN, 1, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser.setGeometry(QtCore.QRect(240, 390, 271, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(20, 220, 281, 41))
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 170, 281, 41))
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.checkBox = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox.setGeometry(QtCore.QRect(170, 280, 21, 31))
        self.checkBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/aa/check.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox.setIcon(icon)
        self.checkBox.setObjectName("checkBox")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(30, 280, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lunch_saved_data_BTN = QtWidgets.QPushButton(self.tab_2)
        self.lunch_saved_data_BTN.setGeometry(QtCore.QRect(20, 320, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.lunch_saved_data_BTN.setFont(font)
        self.lunch_saved_data_BTN.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lunch_saved_data_BTN.setStyleSheet("QPushButton::pressed\n"
"{background-color : rgb(54, 108, 162);\n"
"} \n"
"\n"
" QPushButton{\n"
"background-color: rgb(85, 170, 255);\n"
"border: 2px solid black;\n"
"color: white;padding: 10px;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"display: inline-block;\n"
"font-size: 16px;\n"
"margin: 4px 2px;\n"
"cursor: pointer;\n"
"border-radius: 12px;\n"
"}\n"
"\n"
"")
        self.lunch_saved_data_BTN.setObjectName("lunch_saved_data_BTN")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TT"))
        self.label_6.setText(_translate("MainWindow", "Browser for excel"))
        self.Browse_BTN.setText(_translate("MainWindow", "Browse"))
        self.label_7.setText(_translate("MainWindow", "Selected file:"))
        self.online_check_BTN.setText(_translate("MainWindow", "Online Check"))
        self.Exit_BTN.setText(_translate("MainWindow", "Exit"))
        self.Generate_BTN.setText(_translate("MainWindow", "Generate"))
        self.textBrowser.setPlaceholderText(_translate("MainWindow", "status ..."))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Password"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Username"))
        self.label_5.setText(_translate("MainWindow", "Remember me"))
        self.lunch_saved_data_BTN.setText(_translate("MainWindow", "Use saved data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Excel file Check"))
import a_rc
